config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "posts#index"

  get "users" => "users#index"
  get "users/new" => "users#new"
  get "users/:id" => "users#show"
  post "users/create" => "users#create"

  post "posts/:post_id/comments/create" => "comments#create"
  post "posts/:comment_id/comments/destroy" => "comments#destroy"

  post "posts/:post_id/likes/create" => "likes#create"
  post "posts/:post_id/likes/destroy" => "likes#destroy"

  post "users/:id/follows/create" => "follows#create"
  post "users/:id/follows/destroy" => "follows#destroy"

  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"

  get "login_form" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_follows, class_name: "Follow", dependent: :destroy
  has_many :followings, through: :user_follows
  has_many :user_followers, class_name: "Follow", foreign_key: "followed_user_id"
  has_many :followers, through: :user_followers
  has_one_attached :avatar

  validates :email, presence: true
  validates :password, presence: true
  validates :name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, only: :show

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new params.require(:user).permit(:email, :password, :name)
    if @user.save
      session[:user_id] = @user.id
      flash[:sucsess] = "保存に成功しました"
      redirect_to "/users/new"
    else
      flash[:fail] = "正しい値を入力してください"
      render "users/new"
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:sucsess] = "ログインしました"
      redirect_to "/"
    else
      flash[:fail] = "メールアドレスまたはパスワードが違います"
      render 'login_form'
    end
  end

  def logout
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to "/login_form"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login_form.html.erb
<% if flash[:success] %>
  <%= flash[:success] %>
<% end %>
<% if flash[:fail] %>
  <%= flash[:fail] %>
<% end %>

<%= form_with model: @user, url: login_path, local: true do |form| %>
  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>
  <%= form.submit value: "login" %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録 - newUser</h1>

<%if flash[:fail] %>
  <%= flash[:fail] %>
<% end %>
<%if flash[:sucsess] %>
  <%= flash[:sucsess] %>
<% end %>

<%= form_with model: @user, url: users_create_url, local: true  do |form| %>
  <%= form.label :email %>
  <p><%= form.email_field :email %></p>
  <%= form.label :password %>
  <p><%= form.password_field :password %></p>
  <%= form.label :name %>
  <p><%= form.text_field :name %></p>
  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<p>
  Name: <%= @user.name %>
  <% if @current_user.id == @user.id %>
  <% elsif !Follow.find_by(user_id: @current_user.id, followed_user_id: @user.id)%>
    <%= link_to("フォロー", "/users/#{@user.id}/follows/create", method: "psot") %>
  <% else %>
    <%= link_to("フォロー中", "/users/#{@user.id}/follows/destroy", method: "post") %>
  <% end %>
</p>