config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "posts#index"

  get "users" => "users#index"
  get "users/new" => "users#new"
  get "users/:id" => "users#show"
  post "users/create" => "users#create"

  post "posts/:post_id/comments/create" => "comments#create"
  post "posts/:comment_id/comments/destroy" => "comments#destroy"

  post "posts/:post_id/likes/create" => "likes#create"
  post "posts/:post_id/likes/destroy" => "likes#destroy"

  post "users/:id/follows/create" => "follows#create"
  post "users/:id/follows/destroy" => "follows#destroy"

  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"

  get "login_form" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tag_relationships
  has_many :tags, through: :post_tag_relationships
  has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user
  before_action :set_following_users, only: [:index]

  def index
		@posts = @following_users.map(&:posts).flatten.sort.reverse
  end

  def new
    @post = Post.new
  end

  def create
		@post = Post.create params.permit(:content, :image) # *1
    @post.user_id = @current_user.id
    if @post.save
      flash[:secsess] = "投稿しました"
      redirect_to "/"
		end
    @tag = Tag.find_by(content: params[:tag])
    if @tag
      @post_tag_relation = PostTagRelationship.create(post_id: @post.id, tag_id: @tag.id)
    else
			#@new_tag = Tag.create params.permit(:tag) *1でできてこれでできない理由がわからない
			@new_tag = Tag.create(content: params[:tag]) #これで実装可能
      @post_tag_relation = PostTagRelationship.create(post_id: @post.id, tag_id: @new_tag.id)
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @tags = @post.tags
    @comments = @post.comments
    @like_count = @post.likes.count
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<% if flash[:sucsess] %>
  <%= flash[:sucsess] %>
<% end %>

<div class="postsWrap">
  <% @posts.each do |post| %>
  <% if post.image.attached? %>
    <%= link_to(image_tag(post.image), "/posts/#{post.id}") %>
  <% end %>
  <p>
    <%= link_to post.content, "/posts/#{post.id}" %> /
    <% if @current_user.id == post.user.id %>
      <%= post.user.name %>
    <% else %>
      <%= link_to post.user.name, "/users/#{post.user.id}" %> -
    <% end %>
    <%= post.created_at %>
  </p>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿 - newPost</h1>
<%= form_with url: posts_create_path, local: true do |form| %>
  <p><%= form.text_field :content %></p>
  <p><%= form.file_field :image %></p>
  <p><%= form.text_field :tag %></p>
  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<% if @post.image.attached? %>
  <%= image_tag @post.image, id: "js-post-image" %>
<% end %>
<% if @post.content %>
  <p><%= @post.content %></p>
<% end %>

<% if @tags %>
  <% @tags.each do |tag| %>
    <p><%= tag.content %></p>
  <% end %>
<% end %>
<div data-user-id="<%= @current_user.id %>" data-post-id="<%= @post.id %>" id="js-post-container">

  <p id="js-good-button" data-post-countable="true">Good</p>
  <p id="js-good-count">0</p>

  <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
    <p><%= link_to("unGood!!", "/posts/#{@post.id}/likes/destroy", method: "post") %> / <%= @like_count %></p>
  <% else %>
    <p><%= link_to("Good!!", "/posts/#{@post.id}/likes/create", method: "post") %> / <%= @like_count %></p>
  <% end %>
  <div class="comments_wrap">
    <% @comments.each do |comment| %>
      <p>
        <%= comment.content %> /
        <%= link_to(comment.user.name, "/users/#{comment.user.id}") %> -
        <%= comment.created_at %>
        <% if comment.user_id == @current_user.id %>
          <%= link_to("削除", "/posts/#{comment.id}/comments/destroy", method: "post") %>
        <% end %>
      </p>
    <% end %>
  </div>
  <%= form_with model: Comment.new, url: "/posts/#{@post.id}/comments/create", id: "js-comment-form" do |form| %>
    <p><%= form.text_field :content %></p>
    <%= form.submit value: "投稿" %>
  <% end %>
</div>